max_length_email: 255
max_length_name: 50
min_length_password: 6
gravatar_size: 80
gravatar_size_for_user: 50
password_reset_expired: 2
micropost:
  max_content: 140
  gravatar_size: 50
  picture_size: 5
picture:
  limit_size: 400
feed:
  per_page: 10
per_page: 10
user:
  gravatar_size: 50
show_follow:
  gravatar_size: 30
